version: 0.2
phases:
  install:
    runtime-versions:
      python: 3.11
    commands:
      - echo "Installing dependencies..."
      - pip install -r requiements.txt -t lib
  build:
    commands:
      - echo "Zipping deployment package"
      - cd lib
      - zip -r9 ../deployment_package.zip
      - cd ..
      - zip -g deployment_package.zip lambda_function.py
  post_build:
    - echo "Uploading to S3..."
    - aws s3 cp deployment_package.zip s3://lambda-builds-zip-amal/
    - echo "Updating lambda function via s3..."
    - aws lambda update-function-code --function-name github-to-lambda-cicd --s3-bucket lambda-builds-zip-amal --s3-key deployment_package.zip
    - echo "Depoyment Complete"
